version: '3'

services:
  # app:
  #   build: .
  #   ports:
  #     - "${API_PORT}:9000"
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"
    # volumes:
    #   - ./.postgress-volume-data:/var/lib/postgresql/data